# Generated by Django 3.1.5 on 2021-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_mtr', models.IntegerField()),
                ('jml_mbl', models.IntegerField()),
                ('jml_pdpt', models.BigIntegerField()),
            ],
        ),
    ]
