# Generated by Django 3.1.5 on 2021-01-16 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='layanan',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
        ),
    ]
