# Generated by Django 3.1.5 on 2021-02-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0004_auto_20210202_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='jml_mtr',
            new_name='jml_rd2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='jml_mbl',
            new_name='jml_rd4',
        ),
    ]
